---
title: "Tidy Tuesday, Week 22"
author: "Lyndsay Miles"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, echo=FALSE, include=FALSE, warning=FALSE, message=FALSE}
#libraries
library(tidyverse)
library(tidytuesdayR)
library(ggplot2)
library(plotly)
library(lubridate)
library(ggpubr)
library(extrafont)
```

```{r, echo=FALSE, include=FALSE, warning=FALSE, message=FALSE}
#https://github.com/rfordatascience/tidytuesday/blob/master/data/2024/2024-05-28/readme.md#how-to-participate
#https://www.youtube.com/watch?v=cqi_bCDd6mU Very useful walkthrough on making a sunburst chart

tuesdata <- tidytuesdayR::tt_load(2024, week = 22)
harvest_2020 <- tuesdata$harvest_2020
harvest_2021 <- tuesdata$harvest_2021
planting_2020 <- tuesdata$planting_2020
planting_2021 <- tuesdata$planting_2021
spending_2020 <- tuesdata$spending_2020
spending_2021 <- tuesdata$spending_2021

```

```{r}
harvest_yield_2020 <- harvest_2020 %>%
  group_by(vegetable) %>%
  summarize(yield = sum(weight))%>% 
  mutate(year = 2020)%>%
  arrange(vegetable)

head(harvest_yield_2020)

harvest_yield_2021 <- harvest_2021 %>%
  group_by(vegetable) %>%
  summarize(yield = sum(weight))%>% 
  mutate(year = 2021)%>%
  arrange(vegetable)

harvest_yield_2021$vegetable[harvest_yield_2021$vegetable=="apples"] <- "apple" 

head(harvest_yield_2021)

df_harvest <- harvest_yield_2020 %>% 
  left_join(harvest_yield_2021, by = c("vegetable", "yield", "year"))
```

```{r}
spend_by_veg_2020 <- spending_2020 %>%
  group_by(vegetable) %>% 
  summarize(spend = sum(price_with_tax))

spend_by_veg_2021 <- spending_2021 %>%
  group_by(vegetable) %>% 
  summarize(spend = sum(price_with_tax))
```

```{r}
#Try to make a sunburst graph. 1st level Months, 2nd level type of vegetable, 3rd level variety
library(plotly)
library(lubridate)
library(sunburstR)
df <- planting_2020 %>% 
  mutate(plant_month = format(date, "%m"))%>%
  mutate(plant_month = case_when(
    plant_month == "04" ~ "April",
    plant_month == "05" ~ "May",
    plant_month == "06" ~ "June"
  ))%>%
  select(vegetable, variety, number_seeds_planted, plant_month)%>%
  drop_na()

head(df)
```


```{r}
#install.packages("highcharter")
#install.packages("gapminder")
library(highcharter)
library(gapminder)
```

```{r}
dout_veg <- 
  data_to_hierarchical(
    df, 
    c(plant_month, vegetable), 
    number_seeds_planted)

p1 <-
hchart(dout_veg, 
       type = "sunburst")
```

```{r}

```


```{r}

p2 <- 
  
  highchart() %>%
  hc_chart(type = "sunburst") %>% 
  
  hc_title(text = "Sunburst chart of vegetables planted by month (2020)")%>%
  hc_subtitle(text = "TidyTuesday, Week 22, 2024", style=list(fontSize= "16px", fontWeight = "bold", color = "#d64161"))%>%
  hc_add_series(name = "number_seeds_planted", data = dout_veg)%>%
  hc_credits(enabled= TRUE, text = "Created by: Lyndsay Miles") %>%
  hc_caption(text = "Data Source: TidyTuesday and {gardenR} package") %>%
  hc_add_theme(hc_theme_ft())
p2

```


