---
title: "tt_dubois"
author: "Lyndsay Miles"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# Option 1: tidytuesdayR package 
## install.packages("tidytuesdayR")

tuesdata <- tidytuesdayR::tt_load('2024-04-02')
## OR
#tuesdata <- tidytuesdayR::tt_load(2024, week = 14)

dubois_week10 <- tuesdata$dubois_week10
#Data is from Plate 37 in "W.E.B. Du Bois's Data Portraits: Visualizing Black America: The Color Line at the Turn of the Twentieth Century"
```


```{r}
library(ggplot2)
library(tidyverse)
library(plotly)
```

```{r}
dubois_week10 <- transform(dubois_week10,
                           Occupation = factor(
                             Occupation, 
                             levels = c("Teachers", "Ministers", "Government Service", "Business", "Other Professions", "House Wives"),
                             ordered = TRUE
                           ))

fig <- plot_ly(dubois_week10, 
        labels = ~factor(Occupation, ordered = TRUE), 
        values = ~Percentage, 
        marker = list(colors = c("#BF0A30", "lightblue", "lightpink", "tan", "grey", "gold")),
        type = "pie") %>% 
  layout(title="Results",
         showlegend = T,
         xaxis = list(showgrid = FALSE, zeroline = FALSE, showticklabels = FALSE),
         yaxis = list(showgrid = FALSE, zeroline = FALSE, showticklabels = FALSE)
         )
fig
```
