---
title: "tidytuesday2025"
author: "Lyndsay Miles"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
country_lists <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/main/data/2025/2025-09-09/country_lists.csv')
rank_by_year <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/main/data/2025/2025-09-09/rank_by_year.csv')
```

```{r}
library(tidyverse)
```

```{r}
df_rank <- rank_by_year %>% 
  mutate(tier = case_when(visa_free_count <49 ~ "low", 
                          visa_free_count <98 ~ "medium",
                          visa_free_count <147 ~ "high",
                          visa_free_count > 147 ~ "very high"))
df_lag <- df_rank%>%
  arrange(country, year) %>%
  group_by(country) %>%
  mutate(tier_prev = lag(tier, n = 5)) %>%
  ungroup() %>%
  filter(!is.na(tier_prev))

# Count transitions
transition_counts <- table(df_lag$tier_prev, df_lag$tier)

# Convert to probabilities (row-wise)
transition_matrix <- prop.table(transition_counts, margin = 1)

transition_counts
transition_matrix

library(ggplot2)
as.data.frame(as.table(transition_matrix)) %>%
  ggplot(aes(Var1, Var2, fill = Freq)) +
  geom_tile() +
  geom_text(aes(label = round(Freq, 2)), color = "white") +
  scale_fill_gradient(low = "lightblue", high = "darkblue") +
  labs(x = "Previous Tier", y = "Current Tier", fill = "Probability") +
  theme_minimal()


```

Year-over-year (0.72): 72% of entities in the Low tier one year stayed there the next year. Short-term, the bottom is fairly “sticky.”

Five-year (0.48): Over a five-year window, only 48% remained Low. More than half moved out of the lowest tier within five years—indicating long-term mobility.

```{r}
rank_by_year %>% 
  filter(country == "France") %>% 
  ggplot(aes(x=year, y=visa_free_count))+geom_line()
```

```{r}
eu_countries <- c("Austria", "Belgium", "Bulgaria", "Croatia", "Cyprus", "Czechia", "Denmark", "Estonia", "Finland", "France", "Germany", "Greece", "Hungary", "Ireland", "Italy", "Latvia", "Lithuania", "Luxembourg", "Malta", "Netherlands", "Poland", "Portugal", "Romania", "Slovakia", "Slovenia", "Spain", "Sweden")

fsu <- c(
  "Russian Federation", "Ukraine", "Belarus",
  "Latvia", "Lithuania", "Estonia",
  "Armenia", "Georgia", "Azerbaijan", "Moldova",
  "Kazakhstan", "Kyrgyzstan", "Uzbekistan", "Tajikistan", "Turkmenistan")

sov_sphere <- c(
  "Bosnia and Herzegovina", "Croatia", "Montenegro",
  "Romania", "Poland", "Hungaria", "Romania", "Bulgaria",
  "Albania")

rank_by_year %>% 
  filter(country %in% eu_countries) %>% 
  ggplot(aes(x=year, y=visa_free_count, color = country))+geom_line()

rank_by_year %>% 
  filter(country %in% fsu) %>% 
  ggplot(aes(x=year, y=visa_free_count, color = country))+geom_line()

rank_by_year %>% 
  filter(country %in% sov_sphere) %>% 
  ggplot(aes(x=year, y=visa_free_count, color = country))+geom_line()


```

```{r}
df_change <- rank_by_year %>%
  arrange(country, year) %>%                 # Ensure sorted by country/year
  group_by(country) %>%                      # Compare within each country
  mutate(rankchange3 = rank - lag(rank, n=3),
         rankchange = rank - lag(rank)) %>%  # Difference from previous year
  ungroup()

df_change %>% 
  filter(country %in% sov_sphere) %>% 
  ggplot(aes(x=year, y=visa_free_count, color = country))+geom_line()

p1 <- df_change %>% 
  filter(country %in% fsu) %>% 
  ggplot(aes(x=year, y = rankchange3, color = country)) + geom_line() +
  theme(legend.position = "none")

df_change %>% 
  filter(country %in% fsu) %>% 
  ggplot(aes(x=year, y = rankchange, color = country)) + geom_line() +
  theme(legend.position = "none")
 plt <- plotly::ggplotly(p1)
 plt
 
rank_by_year %>% group_by(region) %>% ggplot(aes(x=year, y=rank, color = country))+geom_line()+facet_wrap(~region)+
  theme(legend.position = "none")
 
df_change %>% filter(region == "AMERICAS") %>% 
  ggplot(aes(x=year, y=rank, color = country)) +
  geom_line()
```

```{r}
df_change_wide <- df_change %>% 
  select(country, year, rank) %>% 
  pivot_wider(names_from = c(country), values_from = rank)
```


```{r}
# Option 2: Read directly from GitHub

all_recipes <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/main/data/2025/2025-09-16/all_recipes.csv')
cuisines <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/main/data/2025/2025-09-16/cuisines.csv')

```

```{r}
library(tidyverse)
library(lubridate)
```


```{r}
cuisines_clean <- cuisines %>% 
  filter(prep_time < 500) 

all_recipes_clean <- all_recipes %>% 
  mutate(year_published = year(date_published))

p1<- all_recipes_clean %>% group_by(year_published) %>% summarize(number_published = n())
ggplot(data = p1, aes(x = year_published, y = number_published))+ geom_line()

ggplot(data = cuisines_clean, aes(x=calories, y = avg_rating))+geom_point()
ggplot(data = cuisines_clean, aes(x=prep_time, y = avg_rating))+geom_point() + scale_y_log10()
```





```{r}
cuisines %>% group_by(country) %>% summarize(n = n())
```

