---
title: "Tidy Tuesday Week 33, 2024: English Monarchs and Marriages"
author: "Lyndsay Miles"
output: html_document
---


My code: https://github.com/LyndsayM/tidy_tuesday_projects/blob/main/tt_2024_33_eng_monarchs.Rmd

My interactive chart: http://rpubs.com/LyndsayM/TT_Eng_Monarchs_2024
```{r setup, echo=FALSE, include=FALSE, warning=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(lubridate)
library(readr)
library(ggplot2)
library(plotly)
library(hrbrthemes)
library(stringr)
```

```{r, echo=FALSE, include=FALSE, warning=FALSE}
# Option 1: tidytuesdayR package 
## install.packages("tidytuesdayR")

tuesdata <- tidytuesdayR::tt_load('2024-08-20')
english_monarchs_marriages_df <- tuesdata$english_monarchs_marriages_df

```

```{r, echo=FALSE, include=FALSE, warning=FALSE}
library(rvest)

# url to scrape:
root <- "https://www.ianvisits.co.uk/articles/a-list-of-monarchs-by-marriage-6857/"

# get table
tables <- read_html(root) |> html_nodes("table")
df <- tables[1] |> html_table() |> as.data.frame()

df <- df[, -6]      # remove spoiler 
df <- df[-c(1,2), ] # remove double-header effect

cols <- c("king_name", "king_age", "consort_name", "consort_age", "year_of_marriage")
colnames(df) <- cols

english_monarchs_marriages_df <- df
```

```{r}
multi_marriages <- c(
  "Æthelred the Unready","Æthelwulf", 
  "Edward the Elder", 
  "Edmund the Magnificent", 
  "Edgar the Peaceful", 
  "Harold Godwinson", 
  "Henry I", 
  "Edward I", 
  "Richard II", 
  "Henry IV", 
  "Henry VIII", 
  "James II", 
  "George IV")

```

```{r}
#cleaning to do - 
#remove question marks, dashes, and parentheses
#change ages from characters to integers
df_clean <- english_monarchs_marriages_df 

df_clean$king_age<- gsub("–","",as.character(df_clean$king_age))
df_clean$king_age<- gsub("\\?","",as.character(df_clean$king_age))
df_clean$king_age<- gsub("\\()","",as.character(df_clean$king_age))
df_clean$king_age<- as.numeric(df_clean$king_age)

df_clean$consort_age<- gsub("–","",as.character(df_clean$consort_age))
df_clean$consort_age<- gsub("\\?","",as.character(df_clean$consort_age))
df_clean$consort_age<- gsub("\\()","",as.character(df_clean$consort_age))
df_clean$consort_age<- as.numeric(df_clean$consort_age)

df_clean$year_of_marriage<- gsub("–","",as.character(df_clean$year_of_marriage))
df_clean$year_of_marriage<- gsub("\\?","",as.character(df_clean$year_of_marriage))
df_clean$year_of_marriage<- gsub("\\()","",as.character(df_clean$year_of_marriage))
df_clean$year_of_marriage<- as.numeric(df_clean$year_of_marriage)

#calculate ratio of king age to consort. does it change over time?
df_clean <- df_clean %>% 
  mutate(age_ratio = king_age/consort_age,
         age_diff = king_age-consort_age,
         multi_marry = if_else(king_name %in% multi_marriages, "yes", "no"))

df_clean$king_name <- as.factor(df_clean$king_name)
df_clean$consort_name <- as.factor(df_clean$consort_name)
```



```{r}
ggplot(data = df_clean, aes(x=year_of_marriage, y = age_ratio))+
  geom_point()+
  scale_y_continuous(trans="log10")

range(df_clean$age_ratio, na.rm = TRUE)
#0.56, 4.17
```



```{r}
p1 <- ggplot(data = df_clean, aes(x=year_of_marriage, y = age_diff, label = "king_name", label = "consort_name"))+
  geom_point(alpha = 1,
             aes(
               color = factor(multi_marry),
               text = paste("Year of Marriage:", year_of_marriage,
                              "<br> King:", king_name,
                              "<br> Consort:", consort_name,
                              "<br> Difference in Age:", age_diff)))+
  labs(title = "English Monarchs and Marriages",
       caption = "Source: Ian Visits by f. hull",
       x = "Year of Marriage",
       y = "Difference in Age")+
  
  scale_color_manual(values = c("#9C95C2", "#3772FF"))+
  guides(colour = FALSE)+
  theme_classic()+
  
p1
```

```{r}
p2 <- ggplot(data = df_clean, aes(x=year_of_marriage, y = age_diff))+
  geom_point(alpha = 1,
             aes(
               color = factor(multi_marry)
               ))+
  labs(title = "TidyTuesday: English Monarchs and Marriages",
       caption = "Source: Ian Visits by f. hull\n Author: Lyndsay Miles",
       color = "Multiple Marriages",
       x = "Year of Marriage",
       y = "Difference in Age")+
  
  scale_color_manual(values = c("#9C95C2", "#3772FF"))+
  #guides(colour = FALSE)+
  theme_classic()
  
p2
```



```{r, echo=FALSE, warning = FALSE}
ggplotly(
 data = p1,
 height = 600,
 width = 850,
 tooltip = "text")%>%
  layout(
    margin = list(b=130,t=100), 
    annotations = list(x = 1, y = -0.2, text = "Source: Ian Visits by f. hull\nAuthor: Lyndsay Miles", 
      showarrow = F, xref='paper', yref='paper', 
      xanchor='right', yanchor='auto', xshift=0, yshift=0,
      font=list(size=12,fontfacet="italic"))
 )
```

```{r, include=FALSE}
ggplot(data = df_clean,
       aes(x=king_age))+
  geom_boxplot()

df_res <- quantile(df_clean$king_age, probs = c(0,0.25,0.5,0.75,1), na.rm = TRUE)
df_res #5 - 0%, 21.25 - 25%, 25 - 50%, 34 - 75%, 60 - 100% 
```

