---
title: "tt_2024_44_monster"
author: "Lyndsay Miles"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(tidytuesdayR)
```


```{r}
# Option 1: tidytuesdayR package 
## install.packages("tidytuesdayR")

tuesdata <- tidytuesdayR::tt_load(2024, week = 44)

monster_movie_genres <- tuesdata$monster_movie_genres
monster_movies <- tuesdata$monster_movies
```

```{r}
#cleanup
library(tidyverse)
library(janitor)

imdb_ratings <- readr::read_tsv(
  "https://datasets.imdbws.com/title.ratings.tsv.gz",
  na = c("", "NA", "\\N")
) |> 
  janitor::clean_names() |> 
  dplyr::filter(num_votes >= 10)
imdb_titles <- readr::read_tsv(
  "https://datasets.imdbws.com/title.basics.tsv.gz",
  na = c("", "NA", "\\N")
) |> 
  janitor::clean_names() |> 
  # A handful of titles have miscoded data, which can be detected by cases where
  # the "isAdult" field has a value other than 0 or 1. That's convenient,
  # because I want to get rid of anything other than 0.
  dplyr::filter(is_adult == 0) |>
  dplyr::select(-is_adult) |>
  dplyr::mutate(
    # Create a column for easier title searching.
    simple_title = tolower(primary_title) |> 
      stringr::str_remove_all("[[:punct:]]")
  )

rated_titles <- imdb_titles |> 
  dplyr::inner_join(imdb_ratings, by = "tconst")

monster_movies <- rated_titles |> 
  dplyr::filter(title_type %in% c("movie", "video", "tvMovie")) |> 
  # "end_year" is only relevant for series.
  dplyr::select(-"end_year") |>
  dplyr::rename("year" = "start_year") |> 
  dplyr::filter(stringr::str_detect(simple_title, "monster")) |> 
  dplyr::mutate(
    dplyr::across(
      c("year", "runtime_minutes", "num_votes"),
      as.integer
    )
  )

monster_movie_genres <- monster_movies |> 
  dplyr::select(tconst, genres) |> 
  tidyr::separate_longer_delim(genres, ",")
```

```{r}
#is there a correlation between runtime and year released?
monster_movies %>% 
  filter(runtime_minutes < 150)%>%
  group_by(year)%>%
  summarize(avg_runtime = mean(runtime_minutes))%>%
  ggplot(aes(x=year, y = avg_runtime))+
  geom_point()
```

```{r}
#is there a correlation between year released and average_rating? Do people 'like' monster movies more during certain times?

df <- monster_movies %>%
  mutate(decade = case_when(year < 1930 ~ "Before 1930",
                            year < 1940 ~ "1930s",
                            year < 1950 ~ "1940s",
                            year < 1960 ~ "1950s",
                            year < 1970 ~ "1960s",
                            year < 1980 ~ "1970s",
                            year < 1990 ~ "1980s",
                            year < 2000 ~ "1990s",
                            year < 2010 ~ "2000s",
                            year < 2020 ~ "2010s",
                            year < 2025 ~ "2020s"))
df_decade <- df %>%   
group_by(decade)%>%
  summarize(avg_average_rating = mean(average_rating))%>%
  ggplot(aes(x=decade, y=avg_average_rating))+
  geom_point()
#highest average ratings are in 1990s and 2000s  
```

```{r}
#what decade produced the most monster movies?
df_most_movies <- df %>% 
  group_by(decade) %>% 
  summarize(num_movies = n())
ggplot(data = df_most_movies, aes(x=decade, y=num_movies))+
  geom_point()

```

```{r}
#is there a relationship between average rating and number of votes?
monster_movies %>% 
  filter(num_votes < 250000)%>%
  ggplot(aes(x = average_rating, y = num_votes))+
  geom_point()
```

```{r}
#relationship between number of votes and year of release?
monster_movies %>%
  ggplot(aes(x= year, y=num_votes))+
  geom_point()+
  geom_vline(xintercept = 1996, col="red")
#num_votes looks like it has more to do with creationn of imdb

```

