---
title: "tt_2025_netflix"
author: "Lyndsay Miles"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
#https://github.com/rfordatascience/tidytuesday/blob/main/data/2025/2025-03-04/readme.md
```

```{r}
# Using R
# Option 1: tidytuesdayR R package 
#tuesdata <- tidytuesdayR::tt_load('2025-08-05')
income_inequality_processed <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/main/data/2025/2025-08-05/income_inequality_processed.csv')
income_inequality_raw <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/main/data/2025/2025-08-05/income_inequality_raw.csv')
```

```{r}
library(ggplot2)
library(tidyverse)

income_inequality_raw %>% drop_na(gini_disposable__age_total) %>%
  ggplot(aes(x = gini_disposable__age_total, y = Entity))+geom_point()
```


```{r}
movies_clean <- movies %>% 
  mutate(showtype = "movie")

shows_clean <- shows %>% 
  mutate(showtype = "show")

df <- rbind(movies_clean, shows_clean)
```

```{r}
ggplot(data = df, aes(x= hours_viewed, y = views)) + geom_point()
ggplot(data = movies_clean, aes(x= hours_viewed, y = views)) + geom_point()
ggplot(data = shows_clean, aes(x= hours_viewed, y = views)) + geom_point()
```

```{r}

```

