---
title: "tt_2025_repro_med"
author: "Lyndsay Miles"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(hrbrthemes)
```

```{r}
# Option 2: Read directly from GitHub

article_dat <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/main/data/2025/2025-02-25/article_dat.csv')
model_dat <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/main/data/2025/2025-02-25/model_dat.csv')
```

```{r}
# Clean data provided by Kat Correia. Student interns extracted this information
# from reproductive medicine journals using duplicate data entry. 
# After duplicate data entry discrepancies were resolved, their 
# individual files were combined, and posted for public access 
# as Google sheets, e.g.,:
# https://docs.google.com/spreadsheets/d/1UuWGQxRU0wxVuOZGYnvkwKn-GdmLIj8kzmUm4KLRHQY/edit?gid=1719021104#gid=1719021104
# No additional cleaning was necessary.
article_dat <- readr::read_csv("https://kcorreia.people.amherst.edu/repro_med_disparities-article-level-data.csv")
model_dat <- readr::read_csv("https://kcorreia.people.amherst.edu/repro_med_disparities-model-level-data.csv")
```

```{r}
#Did the study address disparities in treatment received?
article_dat %>% 
  drop_na(treatment_received) %>%
  group_by(year, treatment_received) %>%
  summarize(num = n())%>% 
  mutate(perc = num/sum(num))%>%
  filter(treatment_received %in% '1') %>% 
  ggplot(aes(x=year, y=perc))+geom_line()
#around 60% of studies addressed disparities beginning in 2012. This has evened out as of 2020
```

```{r}
#what are studies focused on? 
#how many of these studies specifically addressed disparities? I chose four of the variables to think about this: access_to_care, treatment_received, and health_outcome
#access_to_care
access <- article_dat %>% 
  drop_na(access_to_care) %>%
  group_by(year, access_to_care) %>% 
  summarize(num = n())%>%
  mutate(perc = num/sum(num),
         focus = "access")%>%
  filter(access_to_care == '1')%>%
  select(-access_to_care)

#treatment_received
tx_rcvd <- article_dat %>% 
  drop_na(treatment_received) %>%
  group_by(year, treatment_received) %>% 
  summarize(num = n())%>%
  mutate(perc = num/sum(num),
         focus = "treatment_received")%>%
  filter(treatment_received == '1')%>%
  select(-treatment_received)

#health_outcome
hlth_out <- article_dat %>% 
  drop_na(health_outcome) %>%
  group_by(year, health_outcome) %>% 
  summarize(num = n())%>%
  mutate(perc = num/sum(num),
         focus = "health_outcome")%>%
  filter(health_outcome == '1')%>%
  select(-health_outcome)

foci <- bind_rows(access, tx_rcvd, hlth_out) %>% 
  group_by(year)
```

```{r}
foci %>% 
  ggplot(aes(x = year, y = num, fill = focus))+
  #geom_area(aes(fill=focus), position = "stack")+
  geom_area()+
  scale_y_continuous(expand=c(0,0))+
  scale_y_comma()+
  scale_fill_discrete("",
                      labels = c("Access to care", "Health outcomes", "Treatment received"),
                      type = c("darksalmon", "cornsilk", "cornflowerblue"))+
  
  geom_vline(xintercept = 2017, linetype = "dashed")+
  geom_vline(xintercept = 2022, linetype = "dashed")+
    labs(
    title = "Studies addressing disparities in access to care, \nhealth outcomes, and treatment received (2010-2023)",
    x= "",
    y= "",
    subtitle = "Articles on these subjects increased in 2017 and 2022",
    caption = "Source: TidyTuesday, Academic Literature on Racial and \nEthnic Disparities in Reproductive Medicine in the US") +
theme_ipsum_rc(grid="XY")+
  theme(legend.position = "bottom")
```